### ISSUE TITLE
location.js : 세탁방 표시 관련 문제, 지도 확대 level 문제

### ISSUE THREAD

**Issue by Ruan-P** [Ruan-P/buUniv-Campus_Compass#20]
현재 구조가 nav-bar 자체의 텍스트를 검색어로 활용 중인데, '세탁방'의 검색 결과가 원하는 데이터를 표출하지 못하는 문제가 있음

현재 구조로는 세탁방을 표시할 때 현재 GPS 기준으로 가장 가까운 한 곳을 절대적으로 보여주기 때문에 천안권을 벗어나서 출력 중

**Comment by Ruan-P** [comment]
+ 현재 위치를 단 한번 그리는 구조로 잡혀있음. 현위치 초기화 버튼 필요할 듯

**Comment by hashcoko** [comment]
수정했습니다.
